### ISSUE TITLE
It would be nice if I could copy the correct word into my clipboard after selecting the number of that word

### ISSUE THREAD

**Issue by kun-codes** [hisbaan/didyoumean#1]
for example: 
```
❯ dym tomrrow
Did you mean?
1. tomorrow
2. borrow
3. morrow
4. orrow
5. sorrow
```
I want it to be like
```
❯ dym tomrrow -y
Did you mean?
1. tomorrow
2. borrow
3. morrow
4. orrow
5. sorrow

Which word should be copied: 1
"tomorrow" has been copied to your clipboard.
```
`-y` flag stands for yanking the text to clipboard

**Comment by hisbaan** [comment]
This is planned for a very soon future release. I'm actually working on it right now. I wasn't sure what to call the short flag for copied but yank is a good idea! Keep your eyes peeled!

**Comment by kun-codes** [comment]
thanks

**Comment by marcoradocchia** [comment]
I've seen the issue and was trying to implement the same feature myself, thinking about to make a pull request soon.
Nice to see it's already here!
